notifications:
  email: false
sudo: true
os:
- linux
language: node_js
node_js:
- 8.9.1
install:
- npm install
script:
- python build.py
deploy:
- provider: releases
  api_key:
    secure: TDxL0CS+6KJU0qtDokbn88I68Y+rwuBQL3igtH7HsYH0c8BLJMw+dcNE+E26W+3kU99FYRibkXUHRq14T0rxVWsh/HmFfX91kq5M624zUOWbrW/VBwmiXUTCpgvW4ZDHXBWg9KBqiFzn2hqpr4PLwM/VFswI9PxvDYvKjlPFKHWe4JLISiuShMyMQgvuk65zSspkOtmuZMEapnvSbuevGkIYCpnQM8ZotnQ+8NouZ8tgbvi7i70Z4l0Wh7+sa15lv9Jb849SGmsCG4Tog6GKGRqSgOyulEarPuuoY3enANHMvcxCO7sxj1OWSovF0Ot1nmnuV2YLfA65eC1/fRv59nn7vNyAmWmnpqPSTgZz4ah/kyLfAI5p6KUNGkavTwoUfiesrPMnUm0+kSiMthHF/qIlL3sUKN+z0BVDHzfIaMMCmFjRIEWSPgf2O9CXi9ldJZjjamCjmeUKI9CEa2Wr9rndfNdoe1hnbkT4yoF62DDHo5c644cx8HcgZYwXHEESIapwZYzW9xNXHNPCcuDY995+VpbvQ3MElsIoxI4nvKkm0T/0QZPwd8x4g7UCvX7sKlpDW15zCCMapb+oGnuH25ADNQajwiAwrkueqpQvcTuP2Q0P8rGhlh9MXMoHhTn89ISR0s4rj4n9K26fTIisaBFmc0GKZoMsCr9vEQxeLaY=
  file: out/cquery.vsix
  skip_cleanup: true
  on:
    repo: cquery-project/vscode-cquery
    tags: true
- provider: script
  script:
  - ./node_modules/.bin/vsce publish -p $VSCE_LOGIN_PERSONAL_ACCESS_TOKEN --packagePath out/cquery.vsix
  skip_cleanup: true
  on:
    repo: cquery-project/vscode-cquery
    tags: true